### PR TITLE
Fix Rust lifetime highlighting

### PR DESCRIPTION
**Pull request by Delta-official**
before:
Screenshot_20230213_042643

after:
Screenshot_20230213_042635

### CODE REVIEW

**Comment by jgmdev** [comment]
The version of `language_rust` should be bumped on the manifest file.

**Comment by Infinnitor** [comment]
I believe the pattern should be changed to `'%a+[%a%d_]*` to allow for lifetime names with numbers and underscores.

**Comment by Delta-official** [comment]
i believe the pattern `[%a_]+[%a%d_]*` would be more correct

**Comment by adamharrison** [comment]
Can you bump the manifest? I'll merge after that happens.

**Pull request merged**
