### PR TITLE
Add Lite Debugger plugin

### PR DESCRIPTION
**Pull request by Jan200101**
modified from https://github.com/slembcke/debugger.lua

allows developers to interactively debug the lua VM Lite-XL runs on.
different to upstream it also allows for breakpoints to be set on exposed C functions.

### CODE REVIEW

**Comment by Guldoman** [comment]
I wonder if it would be practical to add a command that enables the hooks (and disables them) so that it can be "active" without hurting performance even when not needed.
Otherwise I'd add a big disclaimer in the description that having this enabled *will* hurt performance.

**Comment by adamharrison** [comment]
I think it's reasonable as-is; it does what it says, and people can simply disable it using the normal plugin disable mechanisms or uninstall it if they don't want. I figure if we get complaints about people saying they're getting slowdowns, and don't know why, and they have this installed, then yeah; let's mandate a change to the description, but for now, it's good enough, and works nicely.

**Comment by adamharrison** [comment]
But in the interests of just getting things closed, I'll merge this now, and I'll modify the description to mention the terminal requirement.

**Comment by adamharrison** [comment]
OK, we literally had our first casualty of someone having this problem, so I am going to modify the description and add in the warning lol.

**Pull request merged**
