### PR TITLE
Updated workflow to match new lpm changes.

### PR DESCRIPTION
**Pull request by adamharrison**
If we change `lpm` to remove the table action as per https://github.com/lite-xl/lite-xl-plugin-manager/commit/bccca54916aad5b94eed9b619b6af23b36a6aeda, and have a more generic output format, this is what it'd look like.

### CODE REVIEW

**Comment by adamharrison** [comment]
To be clear, this should only be merged once bccca54 is released.

**Review by Guldoman — COMMENTED** [review]
Might be a good idea to put languages before libraries.

**Comment by adamharrison** [comment]
Yup; done.

**Comment by adamharrison** [comment]
OK, new lpm released. So this should be merged ASAP as the current workflow will fail as the `table` command no longer exists.

**Pull request merged**
