### PR TITLE
Fix `autoinsert.lua`'s behavior on multicursor

### PR DESCRIPTION
**Pull request by AqilCont**
The previous behavior was that it tried to act on the first selection, essentially discarding the ongoing multicursor selection. Now, it properly ignores multicursor.

### CODE REVIEW

**Review by Guldoman — COMMENTED** [review]
Might be a good idea to also limit this predicate:
https://github.com/lite-xl/lite-xl-plugins/blob/cc9a7ba354c28fb3397c3ab65cb83647be02a14f/plugins/autoinsert.lua#L99-L102
so that the commands don't get executed in the multi-cursor case too.

**Review by Guldoman — APPROVED** [review]
Just a couple of nits.

**Comment by Guldoman** [comment]
Oh yeah, might be a good idea to bump the plugin version too.

**Comment by AqilCont** [comment]
Sorry, WDYM bump the plugin version?

**Pull request merged**
