### PR TITLE
added support for Bazel syntax

### PR DESCRIPTION
**Pull request by RohanVashisht1234**

### CODE REVIEW

**Comment by RohanVashisht1234** [comment]
This pr is ready to be merged from my side.

**Review by Guldoman — CHANGES_REQUESTED** [review]
Missing keywords like `True` and `False`.

**Comment by RohanVashisht1234** [comment]
added True and False

**Comment by RohanVashisht1234** [comment]
Updated to the latest version as well

**Comment by RohanVashisht1234** [comment]
Ok, I have updated this pr in a very specific way, now all conflicts have been fixed from my side.

**Pull request merged**
