### PR TITLE
[Plugin] Overwrite

### PR DESCRIPTION
**Pull request by ThaCuber**
it's strange that I haven't yet seen a plugin like this, so I made one
it lets you toggle between inserting characters and overwriting them
I'm making many PRs lately, hope it's not an issue...

### CODE REVIEW

**Comment by adamharrison** [comment]
Not an issue at all. Just tested it. Works great on single cursor, and multi-cursor. Let me just review the code, and then we'll probably be good to go.

**Comment by Guldoman** [comment]
This should probably be a core feature.

**Comment by adamharrison** [comment]
Yeah; honestly, looks great. Merging.

**Comment by adamharrison** [comment]
As per deicison on github, this should be submitted as a core change. Closing.

**Pull request closed without merging**
