### PR TITLE
Minimap Rework with Scrollbar

### PR DESCRIPTION
**Pull request by adamharrison**
Reworked minimap to use Guldoman's new scrollbar class.

### CODE REVIEW

**Comment by adamharrison** [comment]
For clarity: this is essentially complete, with the exception of dragging the viewing window down the minimap. It's ever so slightly off.

**Comment by Guldoman** [comment]
The minimap doesn't seem to cover the entire side of the view when the file is small. Is this intended?
image

IIRC the old plugin covered the full height.

**Comment by adamharrison** [comment]
Oh, interesting. I thought that it didn't, specifically. I'll change that.

**Comment by Guldoman** [comment]
It's working great!

Few minor things I noticed:
* Clicking on the thumb shouldn't scroll.
* Dragging from inside the thumb should keep the click location offset. For example if I start dragging from the top of the thumb, if I move the mouse it should still be at the top of the thumb.
* Clicking on the track shouldn't highlight the thumb.
* Moving the mouse after clicking on the track should either not do anything or make the thumb move immediately under the mouse.

**Comment by adamharrison** [comment]
> Clicking on the thumb shouldn't scroll.
> Dragging from inside the thumb should keep the click location offset. For example if I start dragging from the top of the thumb, if I move the mouse it should still be at the top of the thumb.

Yeah; this is the same problem, due to it not taking into account offset.

> Clicking on the track shouldn't highlight the thumb.

This actually seems to happen on the normal scrollbar. Do we want to remove it specifically for minimap?

> Moving the mouse after clicking on the track should either not do anything or make the thumb move immediately under the mouse.

It currently does nothing. I think that's fine?

**Comment by adamharrison** [comment]
OK, fixed account offset.

**Pull request merged**
