### PR TITLE
Add `tab_switcher`

### PR DESCRIPTION
**Pull request by Guldoman**
This plugin adds a couple of commands to allow switching between tabs by searching their name.

### CODE REVIEW

**Comment by Titousensei** [comment]
Very useful! This would be very nice as a right-click popup on the tab bar.

**Comment by jgmdev** [comment]
What do you think about binding this to `alt+p` by default?

**Comment by Guldoman** [comment]
> What do you think about binding this to `alt+p` by default?

Are there other editors that use that shortcut?

**Comment by jgmdev** [comment]
Since we are already using ctrl+p, ctrl+shift+p I thought alt+p would be convenient

**Comment by Guldoman** [comment]
Should `alt+p` be `tab-switcher:tab-list` or `tab-switcher:tab-list-current-split`?

**Comment by jgmdev** [comment]
`tab-switcher:tab-list` and maybe alt+shift+p `tab-switcher:tab-list-current-split`

**Pull request merged**
