### PR TITLE
Added a bunch of languages

### PR DESCRIPTION
**Pull request by ThaCuber**
- Lox: the funny programming language in Crafting Interpreters
- Umka: an embeddable, statically typed programming language that looks like Go
- Gravity: a class-based concurrent scripting language with a Swift-like syntax

### CODE REVIEW

**Comment by adamharrison** [comment]
Didn't verify the quality of the highlighting, but did verify the syntax of both the files and the manifest, and did a cursory read-through; looks good. Merging.

**Comment by Guldoman** [comment]
We really need to clarify that patterns shouldn't try to match with newlines... Basically every new language that gets added tries to do that.

**Comment by ThaCuber** [comment]
wdym with that?

**Comment by ThaCuber** [comment]
I just realized what did you mean with that, I'll change that when I get back home

**Comment by Guldoman** [comment]
No worries I already got to that. See #252.

**Pull request merged**
