### PR TITLE
Improved language_wren.lua

### PR DESCRIPTION
**Pull request by ThaCuber**
the syntax highlighter *was* fine until I saw it behaving more like Lua's, as if someone just copied Lua's syntax highlighter and pasted it here, then modified it a bit... so I improved the thing
no class or variable outside a class can start with `_`, so I removed the `_` out of `[%a_]` and just left `%a`
and there cannot be a hanging `.` in front or behind a number either, there can't be at the front since `1.floor` and `1.atan(2)` are valid syntax, and there can't be behind because idk
also `if`, `while` and `for` need parentheses and the function section was highlighting those as functions when they aren't
none of the commits make sense either so don't mind them lmao

### CODE REVIEW

**Comment by ThaCuber** [comment]
\*dies*
image

**Comment by ThaCuber** [comment]
ok that should do it 👍

**Comment by ThaCuber** [comment]
that commit name is unclear as fuck, to see those changes you gotta check the commit description

**Comment by jgmdev** [comment]
it is ready for merging?

**Comment by ThaCuber** [comment]
I wanted to highlight the usage of `Fn.new` too so people know it's a standalone function, but I'd say it's done without that

**Comment by jgmdev** [comment]
> I wanted to highlight the usage of `Fn.new` too so people know it's a standalone function, but I'd say it's done without that

"Fn()%.()new", {"type", "type", "type"}?

**Comment by ThaCuber** [comment]
nah, more like the whole `Fn.new`, highlighted as a "keyword2" but I don't know if that is even possible without breaking something else, nor if it will look good on all themes

**Comment by jgmdev** [comment]
so should I merge it as is?

**Comment by ThaCuber** [comment]
yeah, go ahead, it's not that necessary anyways

unless you're me right now
image

**Comment by ThaCuber** [comment]
I have completely forgotten that Wren also has [annotations](https://wren.io/classes#attributes) so I still needed to add more 😔

**Comment by jgmdev** [comment]
another PR :)

**Pull request merged**
