### PR TITLE
Add settings gui plugin

### PR DESCRIPTION
**Pull request by jgmdev**
Initial work on a graphical interface to manage core config options and provide interface to allow plugins specifying config options to display on gui, this is a work in progress, here a video and a screenshot so I can add it to the readme later...

Video:

https://user-images.githubusercontent.com/1702572/164577368-41e89bb6-2dcb-4320-a9c5-412edc7c5679.mp4

Screenshot:

### CODE REVIEW

**Comment by StunxFS** [comment]
Beautiful job!

**Comment by jgmdev** [comment]
For reference, overwrote the toolbarview settings icon to load the settings gui plugin and added a button into General section to open user module:


https://user-images.githubusercontent.com/1702572/165385286-ba6b56f3-87d6-40f3-ac3d-fd2b8ba07440.mp4

**Comment by takase1121** [comment]
Unecessary. This is solved by requiring the plugins before needing to use it. This only brings more z-index problems.

**Comment by jgmdev** [comment]
Added color theme selection pane

**Comment by jgmdev** [comment]
Newer screenshot:

**Pull request merged**
